# Generated by Django 4.0.5 on 2022-07-01 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocks',
            old_name='contenido',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='blocks',
            old_name='fecha',
            new_name='fecha_registro',
        ),
    ]
